# Azure pipeline to deploy to Prod Web app on Azure


trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureWebAppContainer@1
  inputs:
    azureSubscription: 'RMPM'
    appName: 'AppWithContainer'
    containers: 'actionregistry.azurecr.io/nodejsapp:latest'
